[tool.poetry]
name = "django-centralauth"
version = "2.0.0"
description = "App for managing user access and permissions from multiple projects."
authors = [
	"Magdalena Rother <rother.magdalena@gmail.com>",
]
license = "MIT"
readme = "README.rst"
homepage = 'https://github.com/lenarother/django-centralauth'
repository = 'https://github.com/lenarother/django-centralauth'
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"License :: OSI Approved :: MIT License",
	"Environment :: Web Environment",
	"Framework :: Django",
	"Intended Audience :: Developers",
	"Operating System :: Unix",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
]
packages = [{ include = "centralauth" }]
include = ["LICENSE.rst"]

[tool.poetry.dependencies]
python = ">=3.6,<4"
importlib-metadata = {version = "*", python = "<3.8"}

Django = ">=2.2"
Sphinx = {version = ">=3.5", optional = true}

requests = ">=2.25"
requests-oauthlib = ">=1.3"
django-oauth-toolkit = ">=1.5"

[tool.poetry.dev-dependencies]
pytest = ">=6.2"
pytest-cov = ">=2.11"
pytest-flake8 = ">=1.0"
pytest-isort = ">=2.0"
pytest-black = ">=0.3"
coverage = {version = ">=5.5", extras = ["toml"]}

[build-system]
requires = ["poetry>=1.1"]

[tool.pytest.ini_options]
addopts = "-v --tb=short"
testpaths = ["space_game", "tests"]
flake8-max-line-length = 120
flake8-ignore = ["E203", "E266", "E501", "W503"]
flake8-max-complexity = 18

[tool.black]
line-length = 120
skip-string-normalization = true
skip-numeric-underscore-normalization = true
exclude = "/(\\.git|build|dist)/"

[tool.isort]
src_paths = ["space_game", "tests"]
lines_after_imports = 2

[tool.coverage.run]
branch = true
source = ["space_game"]
omit = ["*/__init__.py"]

[tool.coverage.report]
exclude_lines = ["raise NotImplementedError"]